version: '3.9'

services:
  web:
    build: .
    working_dir: /code
    command: sh -c "chmod +x ./wait_for_db.sh && ./wait_for_db.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
