# Generated by Django 5.1.4 on 2024-12-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rationapp', '0006_composition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ration',
            name='selected_ingredients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='count_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='count_pp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ration',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ration',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ration',
            name='organization',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ration',
            name='technologist',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
